### ISSUE TITLE
Polyvoice max causes audio crunch

### ISSUE THREAD

**Issue by dnhushak** [dnhushak/chipophone#13]

**Comment by dnhushak** [comment]
When a lot of keys are down, spits out 

```
Ran out of polyvoices.
```

A number of times.

**Comment by zambreno** [comment]
Wrap all print messages in critical loop around an ifdef debug or something
similar. Prints take thousands of cycles.
Joe

**Comment by dnhushak** [comment]
Good call. I've gone a good job of removing most of the print statements from the loop, that one I didn't. I have a feeling the bug lies elsewhere still, but that should help something.

**Comment by dnhushak** [comment]
Marking this as closed as the dynamic allocation of polyVoices changes the structure enough to where this particular bug doesn't exist. (Not saying it's 100% fixed, but this bug no longer applies)
